web/OneADay/urls.py
from django.conf.urls import url

from OneADay.templates.views import auth_views, account_views


urlpatterns = [
	url(r'^$', account_views.interests, name='interests'),
	url(r'^trending/', account_views.trending, name='trending'),
	url(r'^register/', auth_views.register, name='register'),
	url(r'^login/', auth_views.login_user, name='login'),
	url(r'^logout/', auth_views.logout_user, name='logout'),
	url(r'^add-interest/', account_views.add_interest),
	url(r'^remove-interest/', account_views.remove_interest)
]

web/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('OneADay.urls', namespace="web")),
    url(r'^admin/', include(admin.site.urls)),
]

web/OneADay/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


class Interest(models.Model):
	keyword = models.CharField(db_column='keyword', primary_key=True, max_length=30)
	link = models.CharField(db_column='link', max_length=1000, blank=True, null=True)
	last_updated = models.DateTimeField(db_column='last_updated', blank=True, null=True)

	def __str__(self):
		return self.keyword

	class Meta:
		db_table = 'Interest'


class Subscriber(models.Model):
	subscriberid = models.AutoField(db_column='SubscriberID', primary_key=True)
	user = models.ForeignKey(User, null=False)
	joindate = models.DateTimeField(db_column='join_date')
	last_emailed = models.DateTimeField(db_column='last_emailed', blank=True, null=True)
	frequency = models.IntegerField(db_column="frequency", null=True, default=1)
	keywords = models.ManyToManyField(Interest)

	def __str__(self):
		return self.user.username

	class Meta:
		db_table = 'Subscriber'

web/OneADay/templates/views/account_views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.http import HttpResponse
from django.db import connection

from OneADay.models import Subscriber, Interest


def interests(request):
	if not request.user.is_authenticated() or request.user.username == 'admin':
		logout(request)
		return render(request, 'OneADay/auth/login.html', {'error': ""})

	subscriber = Subscriber.objects.get(user_id=request.user.id)
	keywords = subscriber.keywords.all()
	return render(request, 'OneADay/internal/interests.html', {'interests': keywords})


def add_interest(request):
	if not request.user.is_authenticated() or request.method != 'POST':
		return redirect('web:interests')

	subscriber = Subscriber.objects.get(user_id=request.user.id)
	interest, created = Interest.objects.get_or_create(keyword=request.POST['keyword'])

	subscriber.keywords.add(interest)
	subscriber.save()

	return HttpResponse("Added")


def remove_interest(request):
	if not request.user.is_authenticated() or request.method != 'POST':
		return redirect('web:interests')

	subscriber = Subscriber.objects.get(user_id=request.user.id)
	interest = Interest.objects.get(keyword=request.POST['keyword'])

	subscriber.keywords.remove(interest)
	subscriber.save()

	cursor = connection.cursor()
	cursor.execute("delete from Interest where Keyword not in (select interest_id from Subscriber_keywords)")

	return HttpResponse("Removed")


def trending(request):
	if not request.user.is_authenticated() or request.user.username == 'admin':
		logout(request)
		return render(request, 'OneADay/auth/login.html', {'error': ""})

	return render(request, 'OneADay/internal/trending.html')

web/OneADay/templates/views/auth_views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from datetime import datetime

from OneADay.models import Subscriber


def login_user(request):
	if request.user.is_authenticated():
		return redirect('web:interests')

	if request.method == 'GET':
		return render(request, 'OneADay/auth/login.html', {'error': ""})
	elif request.method != 'POST':
		raise Http404

	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)

	if user is not None:
		login(request, user)
		return redirect('web:interests')

	return render(request, 'OneADay/auth/login.html', {'error': "Incorrect username or password"})


def logout_user(request):
	logout(request)
	return redirect('web:interests')


def register(request):
	if request.method == 'GET':
		return render(request, 'OneADay/auth/register.html', {'error': ""})
	elif request.method != 'POST':
		raise Http404

	username = request.POST['username']
	email = request.POST['email']
	password = request.POST['password']

	if User.objects.filter(email=email).count() > 0:
		return render(request, 'OneADay/auth/register.html', {'error': "That email address is already in use."})

	if User.objects.filter(username=username).count() > 0:
		return render(request, 'OneADay/auth/register.html', {'error': "That username is already in use."})

	user = User.objects.create_user(username, email, password)

	Subscriber.objects.create(user=user, joindate=datetime.now())

	return render(request, 'OneADay/auth/registerSuccess.html', {'name': username})

web/OneADay/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from datetime import datetime
import re

from .models import Subscriber


def index(request):
	if not request.user.is_authenticated():
		return render(request, 'OneADay/auth/login.html', {'error': ""})

	# logout(request)
	subscriber = Subscriber.objects.get(user_id=request.user.id)
	interests = subscriber.keywords.all()
	return render(request, 'OneADay/index.html', {'interests': interests})


def login_user(request):
	if request.user.is_authenticated():
		return redirect('web:index')

	if request.method == 'GET':
		return render(request, 'OneADay/auth/login.html', {'error': ""})
	elif request.method != 'POST':
		raise Http404

	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)

	if user is not None:
		login(request, user)
		return redirect('web:index')

	return render(request, 'OneADay/auth/login.html', {'error': "Incorrect username or password"})

def logout_user(request):
	logout(request)
	return redirect('web:index')

def register(request):
	if request.method == 'GET':
		return render(request, 'OneADay/auth/register.html', {'error': ""})
	elif request.method != 'POST':
		raise Http404

	username = request.POST['username']
	email = request.POST['email']
	password = request.POST['password']

	if User.objects.filter(email=email).count() > 0:
		return render(request, 'OneADay/auth/register.html', {'error': "That email address is already in use."})

	if User.objects.filter(username=username).count() > 0:
		return render(request, 'OneADay/auth/register.html', {'error': "That username is already in use."})

	user = User.objects.create_user(username, email, password)

	Subscriber.objects.create(user=user, joindate=datetime.now())

	return render(request, 'OneADay/auth/registerSuccess.html', {'name': username})

web/OneADay/templates/OneADay/internal/interests.html
{% extends "OneADay/internal/internal.html" %}

{% block internal-includes %}
	<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
	<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.11.4/themes/redmond/jquery-ui.css">


	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'OneADay/plugins/tagit/jquery.tagit.css' %}" />
	<script src="{% static 'OneADay/plugins/tagit/tag-it.js' %}"></script>
	<script src="{% static 'OneADay/js/internal/tagHelper.js' %}"></script>
{% endblock %}

{%  block internal-content %}
	{% csrf_token %}

	<div class="interests">
		<div class="interest-header">
			Interests:
		</div>
		<ul id="interest-tags">
			<!-- Existing list items will be pre-added to the tags -->
			{% for interest in interests %}
				<li>{{ interest.keyword }}</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}

web/OneADay/templates/OneADay/internal/internal.html
{% extends "master.html" %}

{% block includes %}
	{% block internal-includes %}{% endblock %}
	{% load staticfiles %}
	<script src="{% static 'OneADay/js/internal/interests.js' %}"></script>
{% endblock %}

{% block nav-bar %}
	<nav class="navbar navbar-default">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li class="{% ifequal request.path '/'%} active {% endifequal%}"><a href="{% url 'web:interests' %}">Home</a></li>
				<li class="{% ifequal request.path '/trending/'%} active {% endifequal%}"><a href="{% url 'web:trending' %}">Trending</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<span class="glyphicon glyphicon-user" aria-hidden="true" aria-label="user-option"></span><span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">Account Settings</a></li>
						<li role="separator" class="divider"></li>
						<li><a href="#" onclick="document.forms['signOut'].submit()">
							{% csrf_token %}
							<form action="{% url 'web:logout' %}" method="GET" name="signOut"></form>
							Sign Out
						</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</nav>
{% endblock %}

{% block content %}
	{% block internal-content %}{% endblock %}
{% endblock %}

web/OneADay/templates/OneADay/internal/trending.html
{% extends "OneADay/internal/internal.html" %}

{% block internal-includes %}
{% endblock %}

{%  block internal-content %}
	This is the trending topics page.
{% endblock %}

web/OneADay/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.3.min.js"></script>
    <script src="{% static 'OneADay/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" type="text/scss" href="{% static 'OneADay/plugins/bootstrap/css/bootstrap.min.css' %}" />


	{# Local Stylesheets #}
	<link rel="stylesheet" type="text/css" href="{% static 'OneADay/css/main.css' %}" />

    {% block includes %}{% endblock %}

    <meta charset="UTF-8">
    <title>{% block title %}OneADay{% endblock %}</title>
</head>
<body>
	{% block nav-bar %}{% endblock %}
	<div class="container">
        {% block content %}{% endblock %}
	</div>
</body>
</html>